name: HTML Validation

on: [push, pull_request]

jobs:
  validate_html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: . # Specify the root directory to scan for HTML files
          # blacklist: # Optional: Specify files or directories to exclude from validation
          #   - invalid.html
